# Generated by Django 2.0rc1 on 2017-12-02 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='server_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
